### ISSUE TITLE
info

### ISSUE THREAD

**Issue by TihomirS** [alexisvannier/munin-pagespeed#1]
Hi,

I tty to use this plugin with no success on ngx_pagespeed ..
plugin show me data on munin-run pagespeed_
but not draw any graphics .. is there special config on munin plugin.conf ??

Thank you,
Tihomir

**Comment by dorianfm** [comment]
I had a similar problem when I installed it yesterday with nginx. Removing the port checking from the 'autoconf' block fixed it for me, as it was always causing an error otherwise. Nasty, hacky, fix, but might help you.

This is how that block reads in my code now:

```
if ( defined $ARGV[0] and $ARGV[0] eq "autoconf" )
{
        if ($ret)
        {
                print "no ($ret)\n";
                exit 1;
        }

        my $ua = LWP::UserAgent->new(timeout => 30,
                        agent => sprintf("munin/%s (libwww-perl/%s)", $Munin::Common::Defaults::MUNIN_VERSION, $LWP::VERSION));

                print "yes\n";
                exit 0;
}
```

Basically it doesn't do any check on autoconf.

I also symlinked the plugin as

```
pagespeed_bw_saved
pagespeed_cache
pagespeed_css
pagespeed_hit_saved
pagespeed_html
pagespeed_js
```

Hope that helps.

**Comment by TihomirS** [comment]
Thank you @dorianfm !!!
Your hack work on my server too :)
best wishes, T.
